### ISSUE TITLE
No module named 'world'

### ISSUE THREAD

**Issue by BookOwl** [Tymewalk/Tymeventure#10]
^^^

**Comment by Tymewalk** [comment]
So this happens after installing the game, when running `tymeventure`, right?

**Comment by BookOwl** [comment]
Yes

**Comment by Tymewalk** [comment]
OK. I'll try installing it from pip myself, and see what happens there.
Hopefully I should get something useful out of that.
Would you mind copy-pasting the whole error here?

**Comment by BookOwl** [comment]
Here it is:
```
tymeventure
Traceback (most recent call last):
  File "c:\users\matthew\appdata\local\programs\python\python35-32\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\matthew\appdata\local\programs\python\python35-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Matthew\AppData\Local\Programs\Python\Python35-32\Scripts\tymeventure.exe\__main__.py", line 5, in <module>
  File "c:\users\matthew\appdata\local\programs\python\python35-32\lib\site-packages\tymeventure\__init__.py", line 15, in <module>
    from world import * # The world
ImportError: No module named 'world'
```
Also, make sure that you can't import your modules from outside your application's folder when you install, otherwise the installed version will import the world module from your dev version.

**Comment by Tymewalk** [comment]
@BookOwl Yeah, that's probably what I've been doing wrong. I always ran setup.py in the game's folder itself.
I'm trying it the other way now.

**Comment by Tymewalk** [comment]
OK, so now I get this:

       File "/usr/local/bin/tymeventure", line 9, in <module>
         load_entry_point('tymeventure==0.1.1', 'console_scripts', 'tymeventure')()
       File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 351, in load_entry_point
         return get_distribution(dist).load_entry_point(group, name)
       File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2363, in load_entry_point
         return ep.load()
       File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2088, in load
         entry = __import__(self.module_name, globals(),globals(), ['__name__'])
     ImportError: No module named tymeventure
running from my home directory as `python path/to/setup.py build; sudo python path/to/setup.py install`.

**Comment by BookOwl** [comment]
I don't know what would cause that.

**Comment by Tymewalk** [comment]
@BookOwl My own stupidity, probably :tongue:
Anyways, I think that's probably just however I've mucked with the settings.
I'll check and see how to package modules like `world` and `unicurses` in `setup.py`

**Comment by BookOwl** [comment]
Try changing `packages=find_packages(exclude=['contrib', 'docs', 'tests']),` to `packages=["tymeventure"]`

**Comment by Tymewalk** [comment]
@BookOwl Done. Try now.

**Comment by Tymewalk** [comment]
@BookOwl Wow, it's been a while!

But in any case, I appear to have fixed it in the 0.1.2 release. This does mean I have to give up the nice `import world`, but for now it's stable.

**Comment by Tymewalk** [comment]
Adding a high-priority label, if this doesn't get fixed there could be major problems later on.

**Comment by Tymewalk** [comment]
Fixed. The problem was I used `import world` when I should've used `import tymeventure.world`.
