### ISSUE TITLE
Can not run from commandline

### ISSUE THREAD

**Issue by Tymewalk** [Tymewalk/Tymeventure#13]
Traceback (most recent call last):
      File "/usr/local/bin/tymeventure", line 9, in <module>
        load_entry_point('tymeventure==0.1.1', 'console_scripts', 'tymeventure')()
      File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 351, in load_entry_point
        return get_distribution(dist).load_entry_point(group, name)
      File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2363, in load_entry_point
        return ep.load()
      File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2088, in load
        entry = __import__(self.module_name, globals(),globals(), ['__name__'])
    ImportError: No module named tymeventure
    
The game does not run after this. Happens immediately on running from the commandline.

**Comment by Tymewalk** [comment]
Rebuilt using Python 3 and it fixed... kinda. Now it complains about not being able to import `world`.
