### ISSUE TITLE
random is not defined

### ISSUE THREAD

**Issue by BookOwl** [Tymewalk/Tymeventure#18]
```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/tymeventure", line 11, in <module>
    load_entry_point('tymeventure==0.1.2', 'console_scripts', 'tymeventure')()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tymeventure-0.1.2-py3.6.egg/tymeventure/__init__.py", line 432, in main
    gameLoop(stdscr)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tymeventure-0.1.2-py3.6.egg/tymeventure/__init__.py", line 386, in gameLoop
    itemInQuestion.useWith(stdscr, itemToUseWith, currentLocation, inventory)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tymeventure-0.1.2-py3.6.egg/tymeventure/__init__.py", line 170, in pennyUse
    stdscr.addstr(0, 0, "You flip the penny. It comes up " + random.choice(["heads", "tails"]) + ".", unicurses.color_pair(0) | unicurses.A_BOLD)
NameError: name 'random' is not defined
```

**Comment by Tymewalk** [comment]
Thanks for the report.

Adding "prio-high" as this would also break any other uses of `random` in the game.

**Comment by Tymewalk** [comment]
This has just been fixed in the latest development commit (as shown above).
