### ISSUE TITLE
Windows install error

### ISSUE THREAD

**Issue by BookOwl** [Tymewalk/Tymeventure#8]
``` 
tymeventure -h
Traceback (most recent call last):
  File "C:\Users\Matthew\AppData\Local\Programs\Python\Python35-32\Scripts\tymeventure-script.py", line 9, in <module>
    load_entry_point('tymeventure==0.1.0', 'console_scripts', 'tymeventure')()
  File "C:\Users\Matthew\AppData\Local\Programs\Python\Python35-32\lib\site-packages\pkg_resources\__init__.py", line 558, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "C:\Users\Matthew\AppData\Local\Programs\Python\Python35-32\lib\site-packages\pkg_resources\__init__.py", line 2682, in load_entry_point

    return ep.load()
  File "C:\Users\Matthew\AppData\Local\Programs\Python\Python35-32\lib\site-packages\pkg_resources\__init__.py", line 2355, in load
    return self.resolve()
  File "C:\Users\Matthew\AppData\Local\Programs\Python\Python35-32\lib\site-packages\pkg_resources\__init__.py", line 2361, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "C:\Users\Matthew\AppData\Local\Programs\Python\Python35-32\lib\site-packages\tymeventure-0.1.0-py3.5.egg\tymeventure\__init__.py", line 13, in <module>
  File "C:\Users\Matthew\AppData\Local\Programs\Python\Python35-32\lib\curses\__init__.py", line 13, in <module>
    from _curses import *
ImportError: No module named '_curses'
```

**Comment by Tymewalk** [comment]
You might be missing [PDCurses](http://pdcurses.sourceforge.net/) - try installing that, that should fix it.

**Comment by BookOwl** [comment]
I don't have PDCurses, I'll install that and try again.

**Comment by BookOwl** [comment]
You have a glitch with setup.py. You should not list standard library modules, so I can't install the latest version.

**Comment by Tymewalk** [comment]
@BookOwl Like random and pickle?

**Comment by BookOwl** [comment]
Yes. You should only list modules you installed with pip.

**Comment by Tymewalk** [comment]
@BookOwl OK. I've updated it now, so please check if it works.

**Comment by BookOwl** [comment]
@Tymewalk OK

**Comment by BookOwl** [comment]
Now it gives `ImportError: No module named 'world'` :(

**Comment by Tymewalk** [comment]
@BookOwl *facepalms*
I believe @Jonathan50 had the same problem on Scratch. Let me check what solved that...

**Comment by Tymewalk** [comment]
Aaaand it was never solved.
Anyways, the Windows-specific portion was fixed, so would you mind closing this issue and opening a new one for the `No module named 'world'` error (since this problem affects all OSes)?

**Comment by BookOwl** [comment]
OK
